### PR TITLE
omnipay/common ~2.0 and omnipay/tests ~2.0

### PR DESCRIPTION
**Pull request by onlinesid**
Should be backward compatible but I'm using this with a custom Silex project, haven't tested with Silverstripe (which I believe is the intended use of this?)

### CODE REVIEW

**Comment by Big-Shark** [comment]
@jedateach Why you don't merge this PR?

**Comment by onlinesid** [comment]
I think he's very inactive :(

I'll be using Poli in several of my projects in the near future, @jedateach I'll volunteer to help keep this repo updated if you need a hand.

**Comment by onlinesid** [comment]
Damn it ... I pushed the wrong button

**Comment by Big-Shark** [comment]
@onlinesid Maybe if @jedateach continues to be inactive, you should create your project, and register it on https://packagist.org/

**Comment by jedateach** [comment]
Yeah, sorry guys - I'm away from SilverStripe dev presently. I'd talk to the maintainers of shop on anything regarding omnipay.

**Comment by jedateach** [comment]
Anyone want to take over maintenance of this module? - let me know.

**Comment by onlinesid** [comment]
I'll maintain it. I'm using this on one of my projects and possibly more in the future.

**Comment by jedateach** [comment]
thanks @onlinesid. I've given you admin permission for this repo. Let me know if I need to do anything else.

**Comment by onlinesid** [comment]
Thanks @jedateach :)

**Comment by Big-Shark** [comment]
@onlinesid @jedateach thank you, guys.

**Pull request merged**
