### PR TITLE
A few bug fixes, added flexibility & strict typing

### PR DESCRIPTION
**Pull request by tobz-nz**
- added a few more setters to customize more of the purchase request, eg: `merchantData`
- strict return types for safer, more constant ode + helps IDE's with their hinting.
- removed some old code

minimum PHP version set to `>=7.0`

close #6

### CODE REVIEW

**Comment by onlinesid** [comment]
Please squash your commits into one

**Comment by tobz-nz** [comment]
> Please squash your commits into one

Isn't that doe when you merge the PR?

**Comment by onlinesid** [comment]
I guess I can do that too :)

**Comment by tobz-nz** [comment]
This is all working now - I have it implemented into my application 👍

Granted, I have only been using doing Purchases, I've not used the "checkout" request/response - in theory they should be fine though.

**Pull request merged**
