### PR TITLE
Omnipay v3 support.

### LINKED ISSUE #9: Omnipay v3.0?
Any plans to update this for Omnipay 3.0?

### PR DESCRIPTION
**Pull request by tobz-nz**
In theory everything should work in omnipay 3.0 now?
The unit tests are all passing, but I don’t have access to Polipay yet to do some real testing.

Closes #9

### CODE REVIEW

**Comment by onlinesid** [comment]
I have Polipay, just a matter of finding time to try it out

**Comment by tobz-nz** [comment]
So.. it works against the real POLI API then?

**Comment by onlinesid** [comment]
I haven't tested it with real API yet but it passes all unit tests and the code changes look fine to me. I will test with real POLi API before creating an official release for omnipay v3.

**Comment by onlinesid** [comment]
I've created a PHP console script to do a quick test with Omnipay 3.0.3, it seems working, I got a success response from POLi server and I could open the URL returned etc. However I don't have any production environment to do a full end to end test at the moment.

**Comment by tobz-nz** [comment]
Looks promising then 👍
I will give a crack as soon as I have my POLI account setup.

**Pull request merged**
